#!/bin/bash

# Where is the AWS CLI located?
alias aws_location='which aws'

# What version of AWS CLI am I running on?
alias aws_version='aws --version'

# Connect to AWS
alias aws_login='aws sso login'
